### ISSUE TITLE
Tutorial Video Generation with Python doesn't work

### ISSUE THREAD

**Issue by qo4on** [stackbuilders/tutorials#113] opened 2020-02-07 11:53 UTC
[This](https://www.stackbuilders.com/tutorials/python/python-video-generation/) tutorial doesn't work in Colab:
```
!pip install moviepy
import Moviepy.editor as mpy
```

> ModuleNotFoundError: No module named 'Moviepy'

**Comment by Larox** [comment] 2020-02-07 15:00
Hi @qo4on, thanks for your message.

Can you please provide extra information about how you are setting up your `Colab` notebook so I can reproduce the issue and come back with an answer?

**Comment by Larox** [comment] 2020-02-07 15:48
Hi @qo4on, I've reproduced the error and seems to be a typo in the code snippet of the tutorial. This PR #114 will solve this. Remember that all the code for this tutorial can be found [here](https://github.com/stackbuilders/tutorials/tree/tutorials/tutorials/python/python-video-generation/code).

I recommend using `Moviepy` and `Gizeh` versions specified in the [`Pipfile`](https://github.com/stackbuilders/tutorials/blob/3f348d7614debc1374db63064cbc7668c6722fbf/tutorials/python/python-video-generation/code/Pipfile#L12).

Thanks and happy coding!

**Comment by Larox** [comment] 2020-02-07 15:54
Closing issue, fixed in #114

**Closed as completed by Larox** 2020-02-07 15:54 UTC
Labels: bug
